name: docs-release

on:
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install docs deps
        run: |
          python -m pip install --upgrade pip
          pip install ".[docs]"
      
      - name: Inject version into site (optional)
        run: |
          sed -i "s/^site_description:.*/site_description: Docs for $GITHUB_REF_NAME/" mkdocs.yml || true

      - name: Build MkDocs
        run: mkdocs build --strict

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}
